ALTER TABLE channel ADD COLUMN count int(10) unsigned NOT NULL DEFAULT 0;
ALTER TABLE haveread ADD COLUMN count int(10) unsigned NOT NULL DEFAULT 0;
ALTER TABLE channel ADD COLUMN max_message_id BIGINT NOT NULL DEFAULT 0;
